### ISSUE TITLE
Feature request: Allow updating blocks in more detail than second

### ISSUE THREAD

**Issue by gevhaz** [lupont/rbar#1]
The app is really useful, thanks for writing it :)

Some blocks - such as ones presenting "rolling text" - could benefit from updating more than once a second in order to look more natural so if you think this is a good idea, I suggest adding this feature.

**Comment by lupont** [comment]
Thanks a lot! :)
That's a good suggestion. In fact, up until commit [71f262](https://github.com/lupont/rbar/commit/71f262b6121a552d287d18aa679fae781058fb28), the intervals were defined as milliseconds. I changed it to seconds because it felt more natural; but there definitely is value to be able to tune it on an even lower level.

In the latest release, the intervals are defined directly as `std::time::Duration` instances, instead of `u32`:s specifying seconds. This means that you can now use any prefix of seconds you like, as long as the `Duration` API supports it. I hope this is a satisfactory solution!

**Comment by gevhaz** [comment]
That was quick, thanks! Closing.
